apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - image: nginx:1.27.0
      name: nginx-container
      ports:
        - containerPort: 80
# Create object
# cmd: kubectl create -f nginx-pod.yaml
# Get Pods
# cmd: kubectl get pods
# Describe
# cmd: kubectl describe pod <pod-name>
# Auto Generate manifest
# cmd: kubectl run nginx-p --image=nginx:1.27.0 --dry-run=client -o yaml